# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: card-project
  description: ''
  icon: ''
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: Leren trainingsacteren
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ultricies adipiscing sagittis pellentesque dictum ultrices risus molestie egestas. Consectetur adipiscing elit.
  website_url: https://lerentrainingsacteren.nl
  image:
    image: /assets/img/lerentrainingsacteren.png
    alt: Image description

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
