# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: nav
  description: ''
  icon: ''
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  items:
    - title: ''
      url: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  items:
    - title: Home
      url: /
    - title: Examples
      url: ''
    - title: More
      url: ''
      dropdown:
        custom:
          - title: Link A
            url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
